name: "Fraser Lab"
description: "This is the official web page for the James Fraser Lab at UCSF."

url: "http://fraserlab.com"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

collections:
        members:
                output: true
