name: "Fraser Lab @ UCSF"
description: "This is the official web page for the Fraser lab, built in Jekyll by Benjamin Barad"

url: "http://fraserlab.com"

paginate: 5
paginate_path: "news/page:num"

markdown: rdiscount
permalink: pretty
highlighter: pygments